name: Node.js CI
on:
  push:
  pull_request:
  workflow_dispatch:
    branches: [ main ]
    inputs:
      test-value:
        description: 'Test Input'
        type: string
        required: true

jobs:
  build:

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 17
        uses: actions/setup-node@v3
        with:
          node-version: 17.x
      - run: npm ci
      # - run: npm test
